/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhasach;

import Helper.ControlHelper;
import Models.*;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Chau Thinh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    NguoiDung nd = null;

    public MainFrame() {
        initComponents();
        menuDangXuat.setEnabled(true);
                menuThoat.setEnabled(true);
                menuDangNhap.setEnabled(false);
                menuLoaiSach.setEnabled(true);
                menuSach.setEnabled(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDangNhap = new javax.swing.JMenuItem();
        menuDangXuat = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuLoaiSach = new javax.swing.JMenuItem();
        menuSach = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Hệ thống");

        menuDangNhap.setText("Đăng nhập");
        menuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(menuDangNhap);

        menuDangXuat.setText("Đăng xuất");
        menuDangXuat.setEnabled(false);
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(menuDangXuat);

        menuThoat.setText("Thoát");
        menuThoat.setEnabled(false);
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        jMenu1.add(menuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        menuLoaiSach.setText("Loại sách");
        menuLoaiSach.setEnabled(false);
        menuLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoaiSachActionPerformed(evt);
            }
        });
        jMenu2.add(menuLoaiSach);

        menuSach.setText("Sách");
        menuSach.setEnabled(false);
        menuSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSachActionPerformed(evt);
            }
        });
        jMenu2.add(menuSach);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangNhapActionPerformed
        try {
            frmDangNhap fdn = new frmDangNhap(this, true);
            fdn.setVisible(true);
            nd = fdn.getNguoiDung();
            if (nd != null) {
                menuDangXuat.setEnabled(true);
                menuThoat.setEnabled(true);
                menuDangNhap.setEnabled(false);
                menuLoaiSach.setEnabled(true);
                menuSach.setEnabled(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuDangNhapActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        nd = null;
        menuDangXuat.setEnabled(false);
        menuThoat.setEnabled(false);
        menuDangNhap.setEnabled(true);
        menuLoaiSach.setEnabled(false);
        menuSach.setEnabled(false);
    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void menuLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoaiSachActionPerformed
        frmLoaiSach frm;
        try {
            frm = new frmLoaiSach();
            frm.setVisible(true);
            this.add(frm);
            Dimension desktopSize = this.getSize();
            Dimension jInternalFrameSize = frm.getSize();
            frm.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                    (desktopSize.height - jInternalFrameSize.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLoaiSachActionPerformed

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        ControlHelper.getInstance().questionEndWindow(this);
    }//GEN-LAST:event_menuThoatActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ControlHelper.getInstance().questionEndWindow(this);
    }//GEN-LAST:event_formWindowClosing

    private void menuSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSachActionPerformed
        frmSach frm;
        try {
            frm = new frmSach();
            frm.setVisible(true);
            this.add(frm);
            Dimension desktopSize = this.getSize();
            Dimension jInternalFrameSize = frm.getSize();
            frm.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                    (desktopSize.height - jInternalFrameSize.height) / 2);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuDangNhap;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenuItem menuLoaiSach;
    private javax.swing.JMenuItem menuSach;
    private javax.swing.JMenuItem menuThoat;
    // End of variables declaration//GEN-END:variables
}
